//key bindings, all should be lowercase letters
#define MOVE 'q'
#define MOVD 'e'
#define ROTA 'w'
#define DROP 'a'
#define RSET 'l'
#define SNXT 'z'
#define STXT 'c'
#define EXT 'k'
#define TPLS 't'
